### ISSUE TITLE
SharedWorker and ServiceWorker memory attribution

### ISSUE THREAD

**Issue by wanderview** [WICG/performance-memory#17]
Appendix C suggests shared memory should be attributed to a single owner:

https://github.com/WICG/performance-memory/blob/master/explainer.md#-appendix-c---shared-memory

How would this work for web platform features like SharedWorker and ServiceWorker?

SharedWorker instances may be attached to multiple iframes of the same origin across any number of processes.  None of these connections is considered "primary".  Where is the SharedWorker memory attributed?

ServiceWorker threads spawn in reaction to events from clients like iframes, but is not directly connected to any clients.  The ServiceWorker is considered to "control" clients, but same-origin clients that are not controlled can also activate the ServiceWorker using postMessage, etc.  The ServiceWorker can also be activated without any client interaction via things like push messages or background sync.  How is this ServiceWorker memory attributed?

One possible solution is to convert the proposal to report memory per environment instead of per "iframe".  An environment is:

https://html.spec.whatwg.org/multipage/webappapis.html#environment

Each window, iframe, worker (dedicated/shared/service) is a separate environment.  This would avoid having to deal with how these environments interconnect.

**Comment by erikchen** [comment]
Re: per-environment/per-iframe accounting.

Same origin iframes can retain references to both DOM nodes and script in each other. As such, it is semantically unclear how one could attribute memory to a single iframe.

Furthermore, this is one of the most common leaks we've observed in the wild.

Example: 
* iframe A embeds iframe B [same origin]. 
* iframe A has script that retains a closure.
* The closure retains a reference to a DOM node in iframe B
* iframe B is removed from the DOM.

Unfortunately, the closure will still cause iframe A to hold alive much of the memory used by iframe B.

I think the following three statements are equivalent [and necessary]:
* Memory estimate should include the transitive closure of all memory reachable by the current JS execution context.
* Memory estimate should include all environments that have synchronous JS execution.
* Memory estimate should include all same-origin iframes from the current site, and any same-origin sites [transitively] opened via window.open().

What do you think?

note: cross-origin iframes, shared workers and service workers do not satisfy any of the above three statements, and thus need to be considered separately. [Will respond in follow up post].

**Comment by erikchen** [comment]
Re: SharedWorker and ServiceWorker

Thanks for pointing this out. 

In order to be comprehensive, it seems like we should include memory usage from SharedWorker and ServiceWorker. [otherwise a developer could spawn a bunch of SharedWorkers and not realize that it is increasing the memory footprint]. 

Another train of thought: developers don't control the number of tabs that the user has open to a site. If there's only a single tab open, we should obviously count the SharedWorker against that tab. If the user now opens a second tab, we probably *shouldn't* change the memory reported by the first tab, since the only context that changed was outside of the control of the developer.

This means that if there are multiple tabs we'll potentially be counting the memory from the SharedWorker against several different tabs, which overcounts the weight of the SharedWorker on the system. This seems okay since our goal isn't the report the weight of the site on the system, but rather to help developers find their own memory issues.

**Comment by wanderview** [comment]
Ah, sorry.  I read the "provide per-iframe accounting for memory footprint" text in the explainer, but missed that its in the "non-goals" section.  Sorry.

What about providing top level statistics that allow the site owner to do some normalization?  So provides something like:

  * Total origin memory is X
  * Y top level same-origin windows
  * Z other same-origin globals (iframes, workers of all types, worklets, etc)

Then the site could say "we care about memory normalized to a single tab, so we track X / Y".  If they want to do something fancy for shared globals, then they could figure that out given the counts provided.

I'm unclear on what your plans are for cross-origin iframes.  It seems like this probably cannot be included, right?  Otherwise evil.com could frame bank.com and infer logged in state, etc.  It would be a cross-origin information leakage.

**Comment by erikchen** [comment]
> What about providing top level statistics that allow the site owner to do some normalization?

I like this idea!

My only concern would be privacy - if the origin itself is a host for 3rd-party content, then this would allow the 3rd-party content to determine the number of other tabs open to this origin. 

On the other hand, we already have to take the transitive closure of retainable memory, so we're potentially already leaking this information [if other tabs were opened via window.open]. 

This does give us a clean accounting story for shared workers, and allows us to avoid needing to special case window.open().

**Comment by wanderview** [comment]
> My only concern would be privacy - if the origin itself is a host for 3rd-party content, then this would allow the 3rd-party content to determine the number of other tabs open to this origin.

I believe this is observable through APIs like SharedWorker and BroadcastChannel.  Browsers that do 3rd-party partitioning to block this observability would have to make sure to partition the memory reporting as well.

**Comment by erikchen** [comment]
I believe that both of the examples you gave require active collaboration between the tabs.

e.g. geocities.com/A can know the number of other geocities.com/<foo> tabs open by checking GetMemoryEstimate().same_origin_window_count. 

I just thought of another potential concern - This may cause numbers to be conflated across sub-domains whose developers don't wish to be conflated, e.g. mail.google.com vs. docs.google.com.

**Comment by wanderview** [comment]
> I believe that both of the examples you gave require active collaboration between the tabs.

Ok, but I thought you were trying to prevent a tracker.com origin from detecting if it was opened in both a frames and non-framed situation at the same time.  It seems it could collaborate with itself?

> e.g. geocities.com/A can know the number of other geocities.com/ tabs open by checking GetMemoryEstimate().same_origin_window_count.

There is zero safety guarantees between geocities.com/A and geocitities.com/B, right?  I mean, A can inspect B's IDB, they share permissions, etc.  If things are same-origin then we have no way to isolate one from the other AFAIK.

> I just thought of another potential concern - This may cause numbers to be conflated across sub-domains whose developers don't wish to be conflated, e.g. mail.google.com vs. docs.google.com.

Well, I guess it depends on if we are talking about etld+1 "sites" or origins.  Those are different origins, but are same-site.  I thought the memory reporting was per origin, but maybe I'm confused.

**Comment by erikchen** [comment]
My bad. I've apparently been confused about same-origin vs similar-origin for quite some time.

My earlier statement was incorrect. 

* Memory estimate should include the transitive closure of all memory reachable by the current JS execution context.
* Memory estimate should include all same-origin iframes from the current site, and any same-origin sites [transitively] opened via window.open().

Due to document.domain shenanigans, the relevant closure is "[unit of similar-origin browsing contexts](https://html.spec.whatwg.org/multipage/browsers.html#groupings-of-browsing-contexts)". For brevity, I'm going to use the abbreviation USOBC.

So I believe the second statement should be:

* Memory estimate should include all same-[eTLD+1] iframes from the current site, and any same-[eTLD+1] sites [transitively] opened via window.open().

And this should be equivalent to:

* Memory estimate should include the USOBC.

Then the question becomes: should GetMemoryEstimate return:

Option A:
* Total origin + associated USOBCs memory X.
* Y top level (similar-origin?)(same-origin?)(same-origin + USOBC?) windows. 
* Z other (similar-origin?)(same-origin?)(same-origin + USOBC?) globals (iframes, workers of all types, worklets, etc)

Option B:
* USOBC memory X
* Y top level windows in this USOBC.
* Z other globals in this USOBC.

Without USOBCs, returning total origin memory makes sense (Option A). With USOBCs...I'm less sure. I think I'm leaning towards Option B for clarity. Maybe there are other, better options?

**Comment by wanderview** [comment]
> Memory estimate should include the transitive closure of all memory reachable by the current JS execution context.

Does this mean things you can reach synchronously or including async access via stuff like postMessage()?

I still think its not safe to do this for cross-origin iframes that are reachable via postMessage() since it allows cross-origin information leakage.

Anyway, the treatment of origins needs to be clearly defined in the proposal.  Thanks!

**Comment by erikchen** [comment]
I've updated the spec, and attempted to clarify the points we discussed above. 

The [guidelines](https://github.com/WICG/performance-memory/blob/master/explainer.md#guidelines) are now a lot simpler. 

I've avoided the discussion of shared memory entirely - any memory that is required to host the execution context should be included in the memory estimate, including SharedWorkers and ServiceWorkers. The fact that this "overcounts" if there are multiple, unrelated browsing contexts is not interesting to web developers, since that's context dependent and outside of their control.

**Comment by pweis8** [comment]
Thanks Erik! I agree that the "overcounting" between different tabs is not an issue here.

I think it would still be valuable to expose a similar API to workers, to only capture worker memory, especially for shared workers. But that's probably better left for later.

**Comment by wanderview** [comment]
The proposal has been updated to state:

`ServiceWorkers controlling any window, iframe or worker that is otherwise being included in the memory estimate.`

This seems reasonable to me.  It does not include non-controlled service workers, but this is probably a good starting point.  If we wanted to include non-controlled service workers it would probably be best just to include all service workers for the origin.

Thanks!
